# Generated by Django 5.0.6 on 2024-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso'},
        ),
        migrations.AddField(
            model_name='course',
            name='hoursPractice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hoursTeory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='laboratory',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('nameCourse',), name='unique_nameCourse'),
        ),
    ]
