# Generated by Django 5.0.6 on 2024-06-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_course_id_user_created_course_id_user_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_user_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id_user_modified',
        ),
    ]
