# Generated by Django 5.0.6 on 2024-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
