# Generated by Django 5.0.6 on 2024-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_teacher_groups_remove_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
