# Generated by Django 5.0.6 on 2024-06-12 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_career_id_user_created_career_id_user_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='id_user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grades',
            name='id_user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
